baseURL = "http://localhost:1313/"  # Change baseURL to local address
languageCode = "de-de"              # Default language is German
title = "Fifth Generation Construction"
theme = "ananke"
defaultContentLanguage = "en"      # Set English as the default content language
enableRobotsTXT = true

[params]
  mainSections = ["about", "projects"]
  showLanguageSwitcher = true

[languages]
  [languages.de]
    languageName = "Deutsch"
    weight = 1
  [languages.hr]
    languageName = "Hrvatski"
    weight = 2
  [languages.en]
    languageName = "English"
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "about"
  name = "About Us"
  url = "/about/"
  weight = 1

[[menu.main]]
  identifier = "projects"
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  weight = 3
